packages:
  - 'packages/*'
  - 'examples/*'
onlyBuiltDependencies:
  - esbuild
overrides:
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
allowBuilds:
  '@fortawesome/fontawesome-common-types': false
  '@fortawesome/fontawesome-svg-core': false
  '@fortawesome/free-solid-svg-icons': false
  electron: true
  esbuild: true
